from enum import Enum

class Roles(Enum):
    OC_ADMIN = "OC_ADMIN"
    OC_SUPER_ADMIN = "OC_SUPER_ADMIN"
    OC_AGENT = "OC_AGENT"
    OC_MANAGER = "OC_MANAGER"
    OP = "OP"
    PREPOSE = "PREPOSE"
    AGENT_AUTORISATION = "AGENT_AUTORISATION"
    MANAGER_AUTORISATION = "MANAGER_AUTORISATION"
